FROM yassend/ubu-dev-base:latest

# FROM ubuntu:20.04

# RUN echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf.d/85qredo \
#     && apt-get update && apt-get -y dist-upgrade \
#     && apt-get install -y  man-db \
#     && apt-get install -y  sudo vim unzip unrar bash-completion bzip2 \
#                            wget curl gnupg2 ca-certificates \
#     && sed -i 's|^root:\*|root:$6$YjGNqP2VlbvqiiSL$BOF1OHfnaJ1h.lfh31CMZY5RE6ITgJ7WwynFfql7/ULz.kWINq3vyctrFSTExy2A5Y3Z/dBETX/LujL9wODDS.|' /etc/shadow \
#     && sed 's|^root:\*|root:$6$YjGNqP2VlbvqiiSL$BOF1OHfnaJ1h.lfh31CMZY5RE6ITgJ7WwynFfql7/ULz.kWINq3vyctrFSTExy2A5Y3Z/dBETX/LujL9wODDS.|' /etc/shadow > /etc/shad \
#     && chmod 664 /etc/shad
